### ISSUE TITLE
Feature: User can view sample drawings by scrolling through a slideshow carousel (#1)

### ISSUE THREAD

**Issue by Skim-329** [Skim-329/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Once this feature is complete, the user can scroll through sample drawings by scrolling through a slideshow carousel

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

1. The user will click the left and right arrows to scroll back and forth through sample drawings

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="1179" alt="Screen Shot 2021-11-02 at 4 23 54 PM" src="https://user-images.githubusercontent.com/88165545/139965385-60cd9e42-becc-4da6-be02-f6c3cef3068a.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Add a header component which contains the logo to the home page
- [x] Add sample images to images directory
- [x] Add a slideshow carousel component with sample images of 'Bears doing stuff' 
- [x] Ensure that the homepage looks nice on both desktop and mobile screens

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
