### ISSUE TITLE
Feature: User can read about "Bears Doing Stuff" (#2)

### ISSUE THREAD

**Issue by Skim-329** [Skim-329/final-project#13]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can read about 'Bears Doing Stuff'

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will click the 'about' link in the homepage navbar and be directed to another page which displays the About page

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="591" alt="Screen Shot 2021-11-02 at 5 30 45 PM" src="https://user-images.githubusercontent.com/88165545/139969738-58dfc83d-9a3a-4577-ad36-5dd240c9fc49.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Add a nav bar which contains the 'About' link
- [x] Create a component to view 'About page'

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
__
